### PR TITLE
Initial commit libraries-assets

### PR DESCRIPTION
**Pull request by tim-rix**
Creates the S3 bucket, the CloudFront CDN, and the Route53 alias for libraries-assets.mit.edu

### CODE REVIEW

**Comment by vab** [comment]
I believe there are some problems with this code. So, please don't merge it until I have time to investigate further.

**Comment by tim-rix** [comment]
Updated to include a private DNS record.  Now there are both public zone and private zone CNAME records.

**Comment by vab** [comment]
I still don't think this is right. So, please don't merge it. I will explain to you later why.

**Comment by tim-rix** [comment]
Alex,

The **Files changed** tab on the pull request shows the sum of the separate commits...the code that will be merged into Master.  You can look at each separate commit and follow the changes on the **Commits** tab if you want to but the Files changed tab gives you what you were saying you wanted with all commits squashed first.  Can we keep this as is and do a **Squash and Merge** if everything looks good?

--Tim

**Pull request merged**
